### ISSUE TITLE
Cannot compile with libavif master.

### ISSUE THREAD

**Issue by arun54321** [novomesk/qt-avif-image-plugin#4]
```
$./build_libqavif_dynamic.sh                                                                                                          
g++ -c -pipe -Wall -Wextra -O2 -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_PLUGIN -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/include/qt -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtCore -I. -I/usr/lib/qt/mkspecs/linux-g++ -o avif_qt.o avif_qt.cpp
avif_qt.cpp: In member function ‘virtual bool AVIFHandler::write(const QImage&)’:
avif_qt.cpp:472:18: error: ‘avifNclxColorProfile’ {aka ‘struct avifNclxColorProfile’} has no member named ‘fullRangeFlag’
  472 |             nclx.fullRangeFlag = AVIF_NCLX_FULL_RANGE;
      |                  ^~~~~~~~~~~~~
avif_qt.cpp:472:34: error: ‘AVIF_NCLX_FULL_RANGE’ was not declared in this scope
  472 |             nclx.fullRangeFlag = AVIF_NCLX_FULL_RANGE;
      |                                  ^~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:745: avif_qt.o] Error 1
Failed to build libqavif.so

```

**Comment by novomesk** [comment]
Thanks for the info.
Current code works with libavif versions from 0.6.0 to 0.6.4
I will adjust the code but I am waiting for libavif 0.7.2 release.

**Comment by novomesk** [comment]
You may test now. If it works for you, you may close this issue.

**Comment by arun54321** [comment]
It is working now.
